import streamlit as st
from lexer import lexer
from parser import parser
from codegen import generate
from interpreter import MiniPyVM  # ✅ Added VM support

st.set_page_config(page_title="MiniPy (Basic)", layout="wide")
st.title(" MiniPy Compiler - Basic Edition")

code_input = st.text_area("✍️ Enter MiniPy Code", height=300, value="""x = 5
y = 10
if x < y
    print(x + y)
else
    print(x - y)
""")

if st.button("⚙️ Generate Bytecode"):
    try:
        ast = parser.parse(code_input, lexer=lexer)
        bytecode = generate(ast)
        st.subheader("📦 Generated Bytecode")
        st.code("\n".join(bytecode))
    except Exception as e:
        st.error(f"Error while generating bytecode: {e}")

if st.button("▶️ Run in VM"):
    try:
        ast = parser.parse(code_input, lexer=lexer)
        bytecode = generate(ast)
        st.subheader("🖥️ Output (VM Execution)")
        st.text("↓ Output Below ↓")
        with st.echo():
            vm = MiniPyVM(bytecode)
            vm.run()
    except Exception as e:
        st.error(f"Runtime error: {e}")

st.caption("Built with ❤️ for Hackathons using Python, PLY & Streamlit")
